# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeWithFlutterframeworkTest' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for NativeWithFlutterframeworkTest
  pod 'Flutter', :path => './FlutterFramework/engine/'
  pod 'my_flutter', :path => './FlutterFramework/App/'

  target 'NativeWithFlutterframeworkTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeWithFlutterframeworkTestUITests' do
    # Pods for testing
  end

end
